version: '3'
services:
  web:
    build: .
    volumes:
      - type: bind
        source: ./static
        target: /usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - letsencrypt
  letsencrypt:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email --staging -d example.com
    volumes:
      - type: bind
        source: ./static
        target: /var/www/html

